### ISSUE TITLE
运行src的k-Anonymity时会报错，无法运行

### ISSUE THREAD

**Issue by sususnow** [zhhiyuan/K-Anonymity#2]
运行src的k-Anonymity时会报错treelib.exceptions.NodeIDAbsentError: Node 'remove_set.sort(reverse=True)' is not in the tree。无法运行。不知道是哪里出了问题，求助解决。

**Comment by zhhiyuan** [comment]
能否将错误全部上传一下

**Comment by sususnow** [comment]
你好，请问可以提供联系方式吗？似乎Github无法上传图片

**Comment by zhhiyuan** [comment]
qq289919439

**Comment by Arigato97** [comment]
想知道解决了吗 求
